govuk-dotnet-core-template/Models/AddressViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace govuk_dotnet_core_template.Models;

public sealed class AddressViewModel
{
    public string? SearchAddress { get; set; }
    public string? SearchPostCode { get; set; }

    [Required(ErrorMessage = "Enter address line 1")]
    public string? Address1 { get; set; }

    public string? Address2 { get; set; }

    public string? Address3 { get; set; }

    [Required(ErrorMessage = "Enter town or city")]
    public string? TownCity { get; set; }

    [Required(ErrorMessage = "Enter post code")]
    public string? PostCode { get; set; }

    public string? Country { get; set; }
}

govuk-dotnet-core-template/Models/BaseViewModel.cs
namespace govuk_dotnet_core_template.Models;

public class BaseViewModel
{
    /// <summary>
    /// Gets or sets DisplayName.
    /// </summary>
    public string? DisplayName { get; set; }

    /// <summary>Gets or sets the name of the section.</summary>
    /// <value>The name of the section.</value>
    public string? SectionName { get; set; }

    /// <summary>Gets or sets the name of the title tag.</summary>
    /// <value>The name of the title tag.</value>
    public string? TitleTagName { get; set; }
}

govuk-dotnet-core-template/Models/DetailsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace govuk_dotnet_core_template.Models;

public sealed class DetailsViewModel
{
    [Required(ErrorMessage = "Enter your name")]
    [StringLength(100, ErrorMessage = "{0} must be a string with a maximum length of {1}")]
    public string? Name { get; set; }
}

govuk-dotnet-core-template/Models/ErrorViewModel.cs
namespace govuk_dotnet_core_template.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

govuk-dotnet-core-template/Models/GovUkPay.cs
using Newtonsoft.Json;

namespace govuk_dotnet_core_template.Models;

public sealed class GovUkPay
{
    [JsonProperty("amount")]
    public int Amount { get; set; }

    [JsonProperty("reference")]
    public string? Reference { get; set; }

    [JsonProperty("description")]
    public string? Description { get; set; }

    [JsonProperty("return_url")]
    public string? ReturnUrl { get; set; }
}

govuk-dotnet-core-template/Controllers/ApplicationController.cs
using System.Globalization;
using System.Net.Http.Headers;
using System.Text;
using govuk_dotnet_core_template.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace govuk_dotnet_core_template.Controllers;

public class ApplicationController : Controller
{
    private readonly IHttpClientFactory _clientFactory;
    private readonly IConfiguration _configuration;
    private const string WhiteList = "publicapi.payments.service.gov.uk";

    public ApplicationController(IHttpClientFactory clientFactory, IConfiguration configuration)
    {
        _clientFactory = clientFactory;
        _configuration = configuration;
    }

    [HttpGet]
    public IActionResult Start()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Details()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Details(DetailsViewModel model)
    {
        if (ModelState.IsValid)
        {
            return RedirectToAction(nameof(Address));
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult Address()
    {
        var model = new AddressViewModel();

        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Address(AddressViewModel model)
    {
        if (ModelState.IsValid)
        {
            return RedirectToAction(nameof(Summary));
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult Summary()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Summary(BaseViewModel model)
    {
        if (ModelState.IsValid)
        {
            return RedirectToAction(nameof(Pay));
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult Pay()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Pay(BaseViewModel model)
    {
        string baseUrl = $"{this.Request.Scheme}://{this.Request.Host}/application/complete";

        GovUkPay payment = new()
        {
            Amount = 3000,
            Reference = DateTime.Now.ToString(new CultureInfo("en-GB")),
            Description = "Renew your driving licence",
            ReturnUrl = baseUrl
        };

        var client = _clientFactory.CreateClient("GovPay");

        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _configuration["govPaySecretKey"]);

        client.DefaultRequestHeaders.Add("Accept", "application/json");

        var response = await client.PostAsync("payments", new StringContent(JsonConvert.SerializeObject(payment), Encoding.UTF8, "application/json"));

        if (response.IsSuccessStatusCode)
        {
            using HttpContent content = response.Content;
            var responseBody = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
            var dataObj = JObject.Parse(responseBody);

            var nextUrl = dataObj["_links"]?["next_url"]?["href"]?.ToString();

            Response.Cookies.Append(
                "paymentUrl",
                dataObj["_links"]?["self"]?["href"]?.ToString() ?? string.Empty,
                new CookieOptions()
                {
                    Path = "/",
                    HttpOnly = true,
                    Secure = true
                }
            );

            if (nextUrl != null) return Redirect(nextUrl);
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Complete()
    {
        //reading the cookie so we can make a call to see the status of the payment from gov pay.
        string? paymentUrl = Request.Cookies["paymentUrl"];

        if (paymentUrl != null)
        {
            Uri remoteUrl = new Uri(paymentUrl);
            string remoteHost = remoteUrl.Host;

            if (!WhiteList.Contains(remoteHost))
            {
                return BadRequest();
            }
        }

        var client = _clientFactory.CreateClient("GovPay");

        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _configuration["govPaySecretKey"]);

        client.DefaultRequestHeaders.Add("Accept", "application/json");

        var response = await client.GetAsync(paymentUrl);

        if (response.IsSuccessStatusCode)
        {
            var responseBody = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
            var dataObj = JObject.Parse(responseBody);

            var status = dataObj["state"]?["status"]?.ToString();
            ViewData["status"] = status;

            //if not success we assume payment has failed
            if (status != "success")
            {
                var message = dataObj["state"]?["message"]?.ToString();
                var code = dataObj["state"]?["code"]?.ToString();
                if (code != null && message != null)
                    ModelState.AddModelError(code, message);
            }
            else
            {
                // Flash message of success.
                TempData["Success"] = "Payment has been received with thanks";
            }

            Response.Cookies.Delete("paymentUrl");
        }
        return View();
    }
}

govuk-dotnet-core-template/Controllers/HelperController.cs
using Microsoft.AspNetCore.Mvc;

namespace govuk_dotnet_core_template.Controllers;

public class HelperController : Controller
{
    public RedirectToActionResult TimeoutResult()
    {
        return RedirectToAction("Timeout", "Helper");
    }

    [HttpGet]
    public IActionResult Timeout()
    {
        return View();
    }
}

govuk-dotnet-core-template/Controllers/HomeController.cs
using System.Diagnostics;
using govuk_dotnet_core_template.Models;
using Microsoft.AspNetCore.Mvc;

namespace govuk_dotnet_core_template.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Cookies()
    {
        return View();
    }

    public IActionResult Accessibility()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

govuk-dotnet-core-template/Views/Application/Address.cshtml
@model govuk_dotnet_core_template.Models.AddressViewModel

@{
    ViewData["Title"] = "Address";
}

<form asp-action="Address">
@Html.AntiForgeryToken()
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

        <partial name="../Shared/_errorSummary.cshtml" />

            <div class="govuk-form-group">
                <div class="govuk-hint">
                    To find your address, enter a valid Northern Ireland postcode and select find address.
                </div>

                <div class="govuk-form-group" id="PostCodeSearchComponent">
                    <label class="govuk-label" for="SearchPostCode">
                        Postcode
                    </label>
                    <span id="addressError" class="govuk-error-message" style="display:none;">
                        <span class="govuk-visually-hidden">Error:</span> Enter a real postcode
                    </span>

                    <input class="govuk-input govuk-input--width-10" id="SearchPostCode" asp-for="SearchPostCode" type="text" autocomplete="chrome-off">

                    <button class="govuk-button govuk-button--secondary" type="button" data-module="govuk-button" id="btnSearch" onclick="getAddresses();">
                        Find address
                    </button>
                    <div id="loadSpinner" class="govuk-box-highlight" style="display:none;" role="status">
                        <span class="spinner-border"></span>
                        Loading, please wait
                    </div>
                </div>
            </div>

            <div class="govuk-form-group" id="SearchAddressList" style="display:none;">
                <label class="govuk-label" asp-for="SearchAddress">
                    Select an address
                </label>
                <select class="govuk-select" asp-for="SearchAddress" onchange="fillAddressTextBoxes();">
                </select>
            </div>

            <div class="govuk-hint">
                If you cannot find your address, enter your details below.
            </div>
            <div class="govuk-form-group">
                <label asp-for="Address1" class="govuk-label"></label>
                <span asp-validation-for="Address1" class="govuk-error-message"></span>
                <input class="govuk-input govuk-!-width-two-thirds" type="text" asp-for="Address1" autocomplete="address-line1" />
            </div>

            <div class="govuk-form-group">
                <label asp-for="Address2" class="govuk-label">Address Line 2 (optional)</label>
                <input class="govuk-input govuk-!-width-two-thirds" type="text" asp-for="Address2" value="@Model.Address2" autocomplete="address-line2" />
            </div>

            <div class="govuk-form-group">
                <label asp-for="Address3" class="govuk-label">Address Line 3 (optional)</label>
                <input class="govuk-input govuk-!-width-two-thirds" type="text" asp-for="Address3" autocomplete="address-line3" />
            </div>

            <div class="govuk-form-group">
                <label asp-for="TownCity" class="govuk-label">Town or city</label>
                <span asp-validation-for="TownCity" class="govuk-error-message"></span>
                <input class="govuk-input govuk-!-width-two-thirds" type="text" asp-for="TownCity" value="@Model.TownCity" autocomplete="address-level2" />
            </div>

            <div class="govuk-form-group">
                <label asp-for="PostCode" class="govuk-label">Postcode</label>
                <span asp-validation-for="PostCode" class="govuk-error-message"></span>
                <input class="govuk-input govuk-!-width-two-thirds" type="text" asp-for="PostCode" value="@Model.PostCode" autocomplete="postal-code" />
            </div>

        <div class="govuk-form-group">
            <label asp-for="Country" class="govuk-label">Country (optional)</label>
            <input class="govuk-input govuk-!-width-two-thirds" type="text" asp-for="Country" value="@Model.Country" autocomplete="country" />
        </div>

        <div class="govuk-form-group">
            <input type="submit" id="btnContinueSave" value="Save and continue" name="save" class="govuk-button" data-module="govuk-button" />
        </div>

        <div class="govuk-form-group">
            <input type="submit" id="btnSaveClose" value="Save and close" name="save" class="govuk-link link-input" />
        </div>

        <div class="govuk-form-group">
            <partial name="~/Views/Shared/_ContactUsForHelp.cshtml" />
        </div>

    </div>
    </div>
</form>

govuk-dotnet-core-template/Views/Application/Complete.cshtml
@{
    ViewData["Title"] = "Complete";
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <div class="govuk-panel govuk-panel--confirmation">
            <h1 class="govuk-panel__title">
                Application complete
            </h1>
            <div class="govuk-panel__body">
                Your reference number<br><strong>HDJ2123F</strong>
            </div>
        </div>

        <p class="govuk-body">We have sent you a confirmation email.</p>

        <h2 class="govuk-heading-m">What happens next</h2>

        <p class="govuk-body">
            We’ve sent your application to Hackney Electoral Register Office.
        </p>
        <p class="govuk-body">
            They will contact you either to confirm your registration, or to ask for more information.
        </p>

        <p class="govuk-body">
            <a href="#" class="govuk-link">What did you think of this service?</a> (takes 30 seconds)
        </p>
    </div>
    </div>

govuk-dotnet-core-template/Views/Application/Details.cshtml
@model govuk_dotnet_core_template.Models.DetailsViewModel
@{
    ViewData["Title"] = "Details";
}

<form asp-action="Details">
    @Html.AntiForgeryToken()
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">

                <partial name="../Shared/_errorSummary.cshtml" />

                <h1 class="govuk-heading-l">
                    What is your name?
                </h1>

                <div class="govuk-form-group">
                    <label class="govuk-label" asp-for="Name">
                        Name
                    </label>
                    <span asp-validation-for="Name" class="govuk-error-message"></span>
                    <input class="govuk-input" asp-for="Name" type="text" spellcheck="false" autocomplete="given-name">
                </div>
                
                <div class="govuk-form-group">
                    <input type="submit" id="btnContinueSave" value="Save and continue" name="save" class="govuk-button" data-module="govuk-button" />
                </div>

                <div class="govuk-form-group">
                    <input type="submit" id="btnSaveClose" value="Save and close" name="save" class="govuk-link link-input" />
                </div>

                <div class="govuk-form-group">
                    <partial name="~/Views/Shared/_ContactUsForHelp.cshtml" />
                </div>
            </div>
        </div>
</form>

govuk-dotnet-core-template/Views/Application/Pay.cshtml
@model govuk_dotnet_core_template.Models.BaseViewModel
@{
    ViewData["Title"] = "Pay";
}

<form method="post" action="@Url.Action("Pay","Application")">
    @Html.AntiForgeryToken()

            <div class="govuk-grid-row">
                <div class="govuk-grid-column-two-thirds">

                    <a href="" class="govuk-back-link">Back</a>

                    <partial name="../Shared/_errorSummary.cshtml"/>

                    <h1 class="govuk-heading-l">Billable items</h1>

                    <table class="govuk-table">
                        <caption class="govuk-table__caption sr-only">Billable items</caption>
                        <thead>
                        <tr class="govuk-table__row">
                            <th scope="col" class="govuk-table__header">Citizen journey</th>
                            <th scope="col" class="govuk-table__header">Price</th>
                        </tr>
                        </thead>
                        <tbody class="govuk-table__body">

                        <tr class="govuk-table__row">
                            <td class="govuk-table__cell">
                                Renew your licence
                            </td>
                            <td class="govuk-table__cell">
                                £ 30.00
                            </td>
                        </tr>
                        </tbody>
                    </table>

                    <p class="govuk-inset-text">
                        Refer to the Govuk testing guide to select the test card you want to use: <a href="https://docs.payments.service.gov.uk/testing_govuk_pay/" target="blank" rel="nofollow" class="govuk-link">https://docs.payments.service.gov.uk/testing_govuk_pay/</a>
                        e.g. Use 4242424242424242 for VISA debit.
                    </p>

                    <div class="govuk-form-group">
                        <input type="submit" id="btnContinueSave" value="Continue to payment" name="save" class="govuk-button" data-module="govuk-button"/>
                    </div>
                </div>
            </div>
</form>

govuk-dotnet-core-template/Views/Application/Start.cshtml
@{
    ViewData["Title"] = "Start";
}

<div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">

            <partial name="../shared/_errorSummary.cshtml" />

            <h1 class="govuk-heading-l">
                Renew your driving licence
            </h1>

            <p class="govuk-body">
                You cannot use this service to renew a lorry or bus driving licence. You can renew those licences by filling in and returning the renewal reminder form (DL1R)
                if you've been sent one or filling in and returning a driving licence application form (DL2).
            </p>

            <p class="govuk-body">
                You cannot use this service if your last licence was issued before 1 April 1999 and you haven’t had your identity checked. These licences can be renewed by
                filling in and returning a driving licence application form (DL1).
                DL1 and DL2 forms are available from Post Offices.
            </p>

            <a asp-action="Details" asp-controller="Application" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
                Renew your driving licence online
                <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
                    <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
                </svg>
            </a>

            <h2 class="govuk-heading-m">What you need</h2>

            <p class="govuk-body">To renew online, you need:</p>

            <ul class="govuk-list govuk-list--bullet">
                <li>a digital photo or photo code - look at the rules for digital photos before renewing your licence via the green link below </li>
                <li>a credit or debit card (if payment is needed)</li>
                <li>a valid email address</li>
                <li>your NI driving licence number and expiry date - on the plastic card part of your driving licence – ‘5’ is the driving licence number and ‘4b’ the expiry date</li>
            </ul>

            <h2 class="govuk-heading-m">How long it takes</h2>

            <p class="govuk-body">Your driving licence should arrive within 3 week2 if you apply online.</p>

            <p class="govuk-body">You must send your old photocard licence to DVLA when you get your new licence. You’ll be told the address to use when you finish the application.</p>

            <h2 class="govuk-heading-m"> Additional information</h2>

            <p class="govuk-body">If you're unable to provide a digital photo, your licence can be renewed by:</p>

            <ul class="govuk-list govuk-list--bullet">
                <li>filling in and returning a driving licence application form (DL1) - this form is available from Post Offices</li>
            </ul>

            <p class="govuk-body">Watch the video on renewing your driving licence online:</p>

            <iframe width="560" height="315" src="https://www.youtube.com/embed/KS7Drka9bYc" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

        </div>
    </div>

govuk-dotnet-core-template/Views/Helper/Timeout.cshtml
@{
    ViewData["Title"] = "Timeout";
}

<main class="govuk-main-wrapper" id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            <h1 class="govuk-heading-l">Session timed out</h1>
            <p class="govuk-body">
                Your session automatically ends if you don't use this service for 20 minutes.
            </p>
            <a asp-controller="Home" asp-action="Index" role="button" draggable="false" class="govuk-button" data-module="govuk-button">Start again</a>
        </div>
    </div>
</main>

govuk-dotnet-core-template/Views/Home/Accessibility.cshtml
@{
    ViewData["Title"] = "Accessibility";
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        
        <h1 class="govuk-heading-l">
            Accessibility statement for [Service-name]
        </h1>

        <p class="govuk-body">This accessibility statement applies to this service only.</p>
        <p class="govuk-body">This website is run by [Service-name]. We want as many people as possible to be able to use this website. For example, that means you should be able to:</p>
        <ul class="govuk-list govuk-list--bullet">
            <li>change colours, contrast levels and fonts</li>
            <li>zoom in up to 300% without the text spilling off the screen</li>
            <li>navigate most of the website using just a keyboard</li>
        </ul>
        <p class="govuk-body">
            We have also made the website text as simple as possible to understand.
        </p>
        <h1 class="govuk-heading-l">
            How accessible this website is
        </h1>
        <p class="govuk-body">This website is fully accessible.</p>
        <h1 class="govuk-heading-l">
            How to request content in an accessible format
        </h1>
        <p class="govuk-body">If you need information in a different format contact us and tell us:</p>
        <ul class="govuk-list govuk-list--bullet">
            <li>the web address (URL) of the content</li>
            <li>your name and email address</li>
            <li>the format you need, for example, audio CD, braille, <abbr title="British Sign Language">BSL</abbr> or large print, accessible <abbr title="Portable Document Format">PDF</abbr></li>
        </ul>
        <p class="govuk-body">We will consider your request and get back to you in 10 working days</p>
        <h1 class="govuk-heading-l">
            Reporting accessibility problems with this website
        </h1>
        <p class="govuk-body">
            We’re always looking to improve the accessibility of this website. If you find any problems not listed on this page or think we’re not meeting accessibility requirements, contact:
            <a href="mailto:test@tetas.com" class="govuk-link">[Service-name]</a>
        </p>
        <h1 class="govuk-heading-l">
            Enforcement procedure
        </h1>
        <p class="govuk-body">If you contact us with a complaint and you’re not happy with our response <a href="https://www.equalityni.org/contactus" class="govuk-link">contact the Equality Commission for Northern Ireland (ECNI).</a></p>
        <h1 class="govuk-heading-l">Technical information about this website’s accessibility</h1>
        <p class="govuk-body">
            [Service-name] is committed to making its websites accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.
        </p>
        <h1 class="govuk-heading-m">Compliance Status</h1>
        <p class="govuk-body">This website is fully compliant with the <a rel="external" href="https://www.w3.org/TR/WCAG21/" class="govuk-link">Web Content Accessibility Guidelines version 2.1</a> AA standard.</p>

        <h1 class="govuk-heading-m">
            How we tested this website
        </h1>
        <p class="govuk-body">This website was and is currently being tested for compliance with the Web Content Accessibility Guidelines V2.1 level A and level AA, and these tests have been carried out internally.</p>
        <p class="govuk-body">All pages on this website have been tested.</p>

        <h1 class="govuk-heading-m">
            What we’re doing to improve accessibility
        </h1>
        <p class="govuk-body">We plan to identify and fix any issues as quickly as possible.</p>
        <p class="govuk-body">This statement was prepared on 28 January 2022. It was last updated on 28 January 2022.</p>
        <p class="govuk-body-s">Last updated on 01 Nov 2022.</p>
    </div>
</div>

govuk-dotnet-core-template/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        
        <figure>
            <img src="~/assets/images/check-a-service-is-suitable-new.svg" alt="Image of a gov uk process flow" />
        </figure>
         
        <table class="govuk-table">
            <caption class="govuk-table__caption sr-only">Citizen journeys table</caption>
            <thead class="govuk-table__head">
            <tr class="govuk-table__row">
                <th class="govuk-table__header" scope="col">Citizen journey</th>
                <th class="govuk-table__header" scope="col"><span class="sr-only">Action</span></th>
            </tr>
            </thead>
            <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
            <td class="govuk-table__cell">Renew your licence</td>
            <td class="govuk-table__cell">
                <a asp-action="Start" asp-controller="Application" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
                    Start journey
                    <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
                        <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z"/>
                    </svg>
                </a>
            </td>
            </tbody>
        </table>
    </div>
</div>

govuk-dotnet-core-template/Views/Shared/_ContactUsForHelp.cshtml
<details class="govuk-details" data-module="govuk-details">
    <summary class="govuk-details__summary">
        <span class="govuk-details__summary-text">Contact the DVA for help</span>
    </summary>
    <div class="govuk-details__text">
        <ul class="govuk-list">
            <li>Telephone: <a href="tel:03002007861">0300 200 7861</a></li>
        </ul>
        <p class="govuk-body">
            <a class="govuk-link" href="https://www.nidirect.gov.uk/articles/contacting-08-and-03-numbers" target="blank" rel="nofollow">Find out about call charges</a>
        </p>
        <ul class="govuk-list">
            <li><a class="govuk-link" href="mailto:dva@infrastructure-ni.gov.uk">dva@infrastructure-ni.gov.uk</a></li>
            <li><a class="govuk-link" href="https://www.infrastructure-ni.gov.uk/driver-and-vehicle-agency" target="blank" rel="nofollow">https://www.infrastructure-ni.gov.uk</a></li>
        </ul>
    </div>
</details>

govuk-dotnet-core-template/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - govuk_dotnet_core_template</title>
    <meta name="description" content="This is a dotnet template for GDS style site which can be reused on Github for free">
    <meta property="og:url" content="https://gov.uk">
    <link rel="canonical" href="https://gov.uk">
    <meta property="og:title" content="Gov uk dotnet core gds template">
    <meta property="og:description" content="This is a dotnet template for GDS style site">
    <meta property="og:image" content="govuk-opengraph-image.png">
    <meta property="og:image:alt" content="Gov uk template">
    <meta property="og:locale" content="en_GB">
    <meta property="og:type" content="website">
    <meta name="twitter:card" content="summary_large_image"> 
    <link rel="apple-touch-icon" src="~/assets/images/govuk-apple-touch-icon.png" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" href="~/assets/images/favicon.ico" type="image/x-icon" />
    <link rel="icon" sizes="16x16 32x32 48x48" href="~/assets/images/favicon.ico" type="image/x-icon">
    <link href="~/css/jquery.modal.css" rel="stylesheet" />
</head>
<body class="govuk-template__body">
<script>document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>

    <a href="#main-content" class="govuk-skip-link" data-html2canvas-ignore="true">Skip to main content</a>
    <partial name="../Shared/_cookieConsentBanner.cshtml" />
    <partial name="../Shared/_header.cshtml" />

    <div class="govuk-width-container">
        <partial name="../Shared/_alpha.cshtml" />
        <main class="govuk-main-wrapper" id="main-content" role="main">
            @RenderBody()
        </main>
    </div>
    
    <partial name="../Shared/_TimeOutControl.cshtml" />
    <partial name="../Shared/_footer.cshtml" />
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <partial name="../Shared/_ValidationScriptsPartial.cshtml" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
    <partial name="../Shared/_initializeGOVUKFrontend.cshtml" />
    
    <script src="~/js/addresslookup.min.js" asp-append-version="true"></script>
    <script src="~/js/loadspinner.js" asp-append-version="true"></script>
    <script src="~/js/moment.js" asp-append-version="true"></script>
    <script src="~/js/jquery.modal.js" asp-append-version="true"></script>
    <script src="~/js/inactivity-alert.js" asp-append-version="true"></script>
</body>
</html>

govuk-dotnet-core-template/Views/Shared/_initializeGOVUKFrontend.cshtml
<script src="~/js/govuk.min.js"></script>
<script>
    window.GOVUKFrontend.initAll();
</script>